# Generated by Django 5.0 on 2024-06-01 17:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Aircraft',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='IL2StatsServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('url', models.URLField()),
                ('scraper_type', models.CharField(choices=[('il2stats', 'IL2Stats')], default='il2stats', max_length=50)),
            ],
            options={
                'verbose_name': 'IL-2 Stats Server',
                'verbose_name_plural': 'IL-2 Stats Servers',
            },
        ),
        migrations.CreateModel(
            name='PilotStatsPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('pilot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.il2statsserver')),
            ],
            options={
                'verbose_name': 'Pilot Stats Page',
                'verbose_name_plural': 'Pilot Stats Pages',
            },
        ),
        migrations.CreateModel(
            name='VirtualLife',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sortie_points', models.DecimalField(decimal_places=2, max_digits=6)),
                ('air_combat_points', models.DecimalField(decimal_places=2, max_digits=6)),
                ('ground_combat_points', models.DecimalField(decimal_places=2, max_digits=6)),
                ('ship_combat_points', models.DecimalField(decimal_places=2, max_digits=6)),
                ('leadership_points', models.DecimalField(decimal_places=2, max_digits=6)),
                ('nco_points', models.DecimalField(decimal_places=2, max_digits=6)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('number', models.IntegerField()),
                ('flight_time', models.DurationField(default=0)),
                ('was_wounded', models.BooleanField()),
                ('air_kills', models.IntegerField()),
                ('ground_kills', models.IntegerField()),
                ('ship_kills', models.IntegerField()),
                ('pilot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Virtual Lives',
                'ordering': ['pilot', '-number'],
            },
        ),
        migrations.CreateModel(
            name='Sortie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sortie_points', models.DecimalField(decimal_places=2, max_digits=6)),
                ('air_combat_points', models.DecimalField(decimal_places=2, max_digits=6)),
                ('ground_combat_points', models.DecimalField(decimal_places=2, max_digits=6)),
                ('ship_combat_points', models.DecimalField(decimal_places=2, max_digits=6)),
                ('leadership_points', models.DecimalField(decimal_places=2, max_digits=6)),
                ('nco_points', models.DecimalField(decimal_places=2, max_digits=6)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('was_wounded', models.BooleanField()),
                ('air_kills', models.IntegerField()),
                ('ground_kills', models.IntegerField()),
                ('ship_kills', models.IntegerField()),
                ('tour_id', models.IntegerField(default=0)),
                ('sortie_id', models.IntegerField(default=0, unique=True)),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.aircraft')),
                ('virtual_life', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.virtuallife')),
            ],
            options={
                'ordering': ['virtual_life', 'start_at'],
            },
        ),
    ]
