# Generated by Django 5.0 on 2024-06-04 09:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aircraft',
            options={'ordering': ['name'], 'verbose_name': 'Aircraft', 'verbose_name_plural': 'Aircraft'},
        ),
        migrations.AlterModelOptions(
            name='virtuallife',
            options={'ordering': ['pilot', '-number'], 'verbose_name': 'Virtual Life', 'verbose_name_plural': 'Virtual Lives'},
        ),
        migrations.CreateModel(
            name='SomePilot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_on_site', models.IntegerField(unique=True)),
                ('red_occ_count', models.IntegerField(default=0, help_text='Number of times this pilot has been seen on the red side')),
                ('blue_occ_count', models.IntegerField(default=0, help_text='Number of times this pilot has been seen on the blue side')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.il2statsserver')),
                ('squad_pilot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Some Pilot',
                'verbose_name_plural': 'Some Pilots',
                'ordering': ['site', 'id_on_site'],
            },
        ),
        migrations.CreateModel(
            name='PlayerOccurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_created=True)),
                ('coalition', models.CharField(choices=[('blue', 'Blue'), ('red', 'Red')], max_length=10)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.il2statsserver')),
                ('pilot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.somepilot')),
            ],
            options={
                'verbose_name': 'Player Occurrence',
                'verbose_name_plural': 'Player Occurrences',
                'ordering': ['-timestamp', 'server', 'pilot'],
            },
        ),
        migrations.CreateModel(
            name='SomePilotName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('first_seen', models.DateTimeField()),
                ('last_seen', models.DateTimeField()),
                ('ul', models.URLField()),
                ('is_current', models.BooleanField(default=True)),
                ('pilot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.somepilot')),
            ],
            options={
                'verbose_name': "Some pilot's name",
                'verbose_name_plural': 'Some pilot names',
                'ordering': ['-last_seen', 'name'],
                'unique_together': {('is_current', 'pilot')},
            },
        ),
    ]
